name: API Tests with Allure Report

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    schedule:
    - cron: '0 13 * * *'  # Every day at 3:00 PM Cairo time (UTC+2)
    workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run Tests
        run: mvn clean test
        working-directory: API_ITI_Silent_Voice_Allure

      - name: Get Allure history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: API_ITI_Silent_Voice_Allure/target/allure-results
          allure_history: gh-pages

      - name: Publish Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-report
